version: '3.9'
services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monitor
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  local_api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -e /workspace && python -m uvicorn apps.local_api.main:app --host 0.0.0.0 --port 18000"
    volumes: ["../..:/workspace"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/monitor
    depends_on: [db]
    ports: ["18000:18000"]
  archiver:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -e /workspace && python apps/archiver/main.py"
    volumes: ["../..:/workspace"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/monitor
      - S3_BUCKET=my-bucket
      - S3_PREFIX=monitoring/
      - SITE_ID=fab1
    depends_on: [db]
