version: '3.8'

# Data Plane Component - Independent Deployment
# Includes: Local API + Central API + Archiver + TimescaleDB

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: wafer-timescaledb
    environment:
      - POSTGRES_USER=wafer
      - POSTGRES_PASSWORD=wafer
      - POSTGRES_DB=wafer_local
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../components/data-plane/database/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ../../components/data-plane/database/sql/timescaledb_enhancements.sql:/docker-entrypoint-initdb.d/02-enhancements.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wafer"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - data-plane

  local-api:
    image: ghcr.io/theoverflow/trackmate/local-api:latest
    container_name: wafer-local-api
    build:
      context: ../../components/data-plane
      dockerfile: Dockerfile.local-api
    ports:
      - "18000:18000"
    environment:
      - DATABASE_URL=postgresql://wafer:wafer@timescaledb:5432/wafer_local
      - DB_POOL_MIN_SIZE=5
      - DB_POOL_MAX_SIZE=20
      - LOG_LEVEL=INFO
    depends_on:
      timescaledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18000/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - data-plane

  central-api:
    image: ghcr.io/theoverflow/trackmate/central-api:latest
    container_name: wafer-central-api
    build:
      context: ../../components/data-plane
      dockerfile: Dockerfile.central-api
    ports:
      - "19000:19000"
    environment:
      - LOG_LEVEL=INFO
      - SITE_URLS=http://local-api:18000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19000/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - data-plane

  archiver:
    image: ghcr.io/theoverflow/trackmate/archiver:latest
    container_name: wafer-archiver
    build:
      context: ../../components/data-plane
      dockerfile: Dockerfile.archiver
    environment:
      - DATABASE_URL=postgresql://wafer:wafer@timescaledb:5432/wafer_local
      - S3_BUCKET=wafer-archive
      - S3_ENDPOINT=http://minio:9000
      - ARCHIVE_INTERVAL_HOURS=24
      - LOG_LEVEL=INFO
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - data-plane

volumes:
  postgres-data:

networks:
  data-plane:
    name: wafer-data-plane
    driver: bridge

