name: Web Component CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'components/web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/web/**'

jobs:
  test:
    name: Test Web Component
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-web-${{ hashFiles('components/web/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-web-
    
    - name: Install dependencies
      run: |
        cd components/web
        pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        cd components/web
        ruff check local-dashboard/ central-dashboard/
    
    - name: Run tests
      run: |
        cd components/web
        pytest tests/ -v --cov=. --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: components/web/coverage.xml
        flags: web
        name: web-${{ matrix.python-version }}

  build-local-dashboard:
    name: Build Local Dashboard Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Local Dashboard
      uses: docker/build-push-action@v5
      with:
        context: components/web
        file: components/web/Dockerfile.local-dashboard
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/local-dashboard:latest
          ghcr.io/${{ github.repository }}/local-dashboard:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-central-dashboard:
    name: Build Central Dashboard Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Central Dashboard
      uses: docker/build-push-action@v5
      with:
        context: components/web
        file: components/web/Dockerfile.central-dashboard
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/central-dashboard:latest
          ghcr.io/${{ github.repository }}/central-dashboard:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    name: Deploy Web Component
    runs-on: ubuntu-latest
    needs: [build-local-dashboard, build-central-dashboard]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to staging
      run: |
        echo "Deploying web component to staging..."
        # Add your deployment script here

